services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    command: ["mongod", "--bind_ip_all", "--auth"]
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: api
        ENVIRONMENT: localhost
    container_name: backend-api
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - .env.docker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend_network
    volumes:
      - ./.docker/logs:/usr/src/app/logs    
networks:
  backend_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
