package repositories

import (
	"context"
	"errors"
	"time"

	"backend-service/internal/domain"
	"backend-service/internal/infrastructure/database/models"

	"go.mongodb.org/mongo-driver/mongo"
)

func (r *Repo) CreateUser(user domain.User) error {
	// Create a context with a timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Map domain.User to models.UserModel
	dbModel := models.UserModel{
		// ID will be auto-generated by MongoDB if omitempty is set and ID is zero value
		Name:      user.Name,
		Email:     user.Email,
		Password:  user.Password,
		CreatedAt: time.Now(),
	}

	// Get the "users" collection
	collection := r.db.Collection("users")

	// Insert the user document
	_, err := collection.InsertOne(ctx, dbModel)
	if err != nil {
		// Check if the error is a duplicate key error (email already exists)
		if mongo.IsDuplicateKeyError(err) {
			return errors.New("email already exists")
		}
		return err
	}

	return nil
}
