package repositories

import (
	"context"
	"errors"
	"time"

	"backend-service/internal/domain"
	"backend-service/internal/infrastructure/database/models"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func (r *Repo) CreateUser(user domain.User) error {
	// Create a context with a timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Map domain.User to models.UserModel
	dbModel := models.UserModel{
		// ID will be auto-generated by MongoDB if omitempty is set and ID is zero value
		Name:      user.Name,
		Email:     user.Email,
		Password:  user.Password,
		CreatedAt: time.Now(),
	}

	// Get the "users" collection
	collection := r.db.Collection("users")

	// Insert the user document
	_, err := collection.InsertOne(ctx, dbModel)
	if err != nil {
		// Check if the error is a duplicate key error (email already exists)
		if mongo.IsDuplicateKeyError(err) {
			return errors.New("email already exists")
		}
		return err
	}

	return nil
}

func (r *Repo) GetUserByEmail(email string) (*domain.User, error) {
	// Create a context with a timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Get the "users" collection
	collection := r.db.Collection("users")

	// Find user by email
	var userModel models.UserModel
	err := collection.FindOne(ctx, bson.M{"email": email}).Decode(&userModel)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, errors.New("user not found")
		}
		return nil, err
	}

	// Map models.UserModel to domain.User
	user := r.convertUserModelToEntityWithPassword(userModel)

	return user, nil
}

func (r *Repo) GetUserByID(id string) (*domain.User, error) {
	// Create a context with a timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Convert string ID to ObjectID
	objectID, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, errors.New("invalid user ID format")
	}

	// Get the "users" collection
	collection := r.db.Collection("users")

	// Find user by ID
	var userModel models.UserModel
	err = collection.FindOne(ctx, bson.M{"_id": objectID}).Decode(&userModel)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, errors.New("user not found")
		}
		return nil, err
	}

	// Map models.UserModel to domain.User
	user := r.convertUserModelToEntity(userModel)

	return user, nil
}

func (r *Repo) GetUsersWithPagination(page, limit int) ([]*domain.User, int, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	collection := r.db.Collection("users")
	filter := bson.M{} // Empty filter to get all users

	// Get total count first
	totalCount, err := collection.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	// Calculate pagination values
	skip := (page - 1) * limit
	skipValue := int64(skip)
	limitValue := int64(limit)

	// Set up find options for pagination
	findOptions := &options.FindOptions{
		Skip:  &skipValue,
		Limit: &limitValue,
		Sort:  bson.D{{Key: "createdAt", Value: -1}}, // Newest first
	}

	// Execute the query
	cursor, err := collection.Find(ctx, filter, findOptions)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	// Decode results
	var userModels []models.UserModel
	if err = cursor.All(ctx, &userModels); err != nil {
		return nil, 0, err
	}

	// Convert to domain entities
	users := r.convertUserModelsToEntities(userModels)

	return users, int(totalCount), nil
}

// convertUserModelsToEntities converts database models to domain entities
func (r *Repo) convertUserModelsToEntities(userModels []models.UserModel) []*domain.User {
	users := make([]*domain.User, 0, len(userModels))

	for _, userModel := range userModels {
		user := r.convertUserModelToEntity(userModel)
		users = append(users, user)
	}

	return users
}

// convertUserModelToEntity converts a single database model to domain entity
func (r *Repo) convertUserModelToEntity(userModel models.UserModel) *domain.User {
	return &domain.User{
		ID:        userModel.ID.Hex(),
		Name:      userModel.Name,
		Email:     userModel.Email,
		CreatedAt: &userModel.CreatedAt,
	}
}

// convertUserModelToEntityWithPassword converts a single database model to domain entity including password
func (r *Repo) convertUserModelToEntityWithPassword(userModel models.UserModel) *domain.User {
	user := r.convertUserModelToEntity(userModel)
	user.Password = userModel.Password
	return user
}
